// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gofdnsvrwamujqmkpwzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvZmRuc3Zyd2FtdWpxbWtwd3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzkyNTIsImV4cCI6MjA3MTcxNTI1Mn0.0gV042WuGglLJ-UHCnkkouVwHyBmxRFS7meYgKfzoeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});